version: '3'

networks: 
 network_practica:

volumes:
  myGrafanaVol:
  datasources.yml:

services: 

 #node
 myapp_practica:
  build: .
  ports: 
   - "83:3000"
  networks:
   - "network_practica"
 
 #prometheus
 prometheus:
  image: prom/prometheus:v2.20.1
  container_name: prometheus_practica
  ports: 
   - "9090:9090"
  volumes: 
   - "./prometheus:/etc/prometheus"
  depends_on: 
   - myapp_practica
  command: --config.file=/etc/prometheus/prometheus.yml
  networks:
   - "network_practica"

 #grafana
 grafana:
  image: grafana/grafana:7.1.5 
  container_name: grafana_practica
  ports:
    - "3500:3000"
  volumes:
    - myGrafanaVol:/var/lib/grafana
    - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
  depends_on: 
   - prometheus
  environment:
    - GF_AUTH_DISABLE_LOGIN_FORM=true
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    - GF_INSTALL_PLUGINS=grafana-clock-panel 1.0.1
  networks:
   - "network_practica"

